version: "2.2"

services:
  zombie-401:
    build:
      context: ../zombie-common
      dockerfile: ../zombie-common/Dockerfile
      args:
        configFile: '{"flag": "find-the-secret-flag" ,"httpOnly": false, "allowDebug": true, "secret-flag": "wctf{redacted}"}'

    image: zombie-401:1
    container_name: zombie-401
    init: true
    restart: always
    ports:
      - "80:80"
