version: "2.2"

services:
  zombie-201:
    build:
      context: ../zombie-common
      dockerfile: ../zombie-common/Dockerfile
      args:
        configFile: '{"flag": "wctf{redacted}", "httpOnly": true, "allowDebug": true}'

    image: zombie-201:1
    container_name: zombie-201
    init: true
    restart: always
    ports:
      - "80:80"
